#!/usr/bin/perl -w

#** @file HidTEMPer.pl
# @verbatim
#####################################################################
# This program is not guaranteed to work at all, and by using this  #
# program you release the author of any and all liability.          #
#                                                                   #
# You may use this code as long as you are in compliance with the   #
# license (see the LICENSE file) and this notice, disclaimer and    #
# comment box remain intact and unchanged.                          #
#                                                                   #
# Class:       bcmHidTEMPer                                         #
# Description: munin plugin for HidTEMPer sensor                    #
#                                                                   #
# Written by:  Imran Shamshad (sid@projekt-turm.de)                 #
##################################################################### 
# @endverbatim
#
# @copy 2011, Imran Shamhad (sid@projekt-turm.de)
# $Id: $HidTEMPer.pl
#*

#** replace with "basedir" or so
BEGIN { push @INC, '/opt/rpi-sensors/lib' }

use strict;
use warnings;

use sensors;
use Munin::Plugin;

my $sensorID;

if( !($0=~ m\dht11_(.*)\) ){
	die "unable to read ID of DHT11 from filename";
}
$sensorID = $1;

if (defined $ARGV[0] && $ARGV[0] eq 'autoconf') {
	if( !(getDHT11($sensorID) eq "U") ){
		print "yes\n";
		exit(0);
	} else {
		print "no\n";
		exit(1);
	}
}

if (defined $ARGV[0] && $ARGV[0] eq 'config') {
print <<EOM;
graph_title humidity and temperature of DHT11 sensor $sensorID
graph_args --upper-limit 200 -l -50
graph_vlabel °C and %
graph_category sensors

temp.label °C
temp.warning 15.0:30.0
temp.critical 10.0:40.0

humi.label %
humi.warning 20.0:50.0
humi.critical 10.0:60.0
EOM
exit(0);
}
else{
	my @temp;
	my $fh;
	my $storage;

	open ($fh, "+</tmp/cron/dht11-$sensorID") || die "cant open file: $!\n";
	$storage = <$fh>;
	close $fh;

	chomp($storage);
	@temp = split(' ', $storage);
#	($temp, $humi) = avgTemp(\&getDHT11, 1, 3, 3, $sensorID);

	print "temp.value $temp[0]\n";
	print "humi.value $temp[1]\n";
}
